# Generated by Django 3.2.9 on 2021-12-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_lead_converted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Google', 'Google'), ('Instagram', 'Instagram'), ('Twitter', 'Twitter'), ('Referral', 'Referral'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
