# Generated by Django 3.2.9 on 2021-12-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Agent', 'Agent'), ('Expense Manager', 'Expense Manager')], default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
