# Generated by Django 3.2.9 on 2021-12-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_auto_20211207_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Agent', 'Agent'), ('Expense Manager', 'Expense Manager')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Agent', 'Agent'), ('Expense Manager', 'Expense Manager')], default='other', max_length=20),
        ),
    ]
