# Generated by Django 3.2.9 on 2021-12-08 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_auto_20211207_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_organisor',
            new_name='is_admin',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('other', 'Other'), ('Admin', 'Admin'), ('Agent', 'Agent'), ('Expense Manager', 'Expense Manager')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('Agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.agent')),
            ],
        ),
    ]
